#ifndef HOOK_H
#define HOOK_H

#define STATUS_ACCESS_DENIED 0xC0000022
#define PE_SIGNATURE 0x4550
#define SHA256_DIGEST_LENGTH 32
#define MAX_API_ARGS 10 
#define HEARTBEAT_INTERVAL 20000
#define INTEGRITY_CHECK_INTERVAL 30000
#define COUNTER_LOOP_SLEEP_INTERVAL 10000
#define HOOK_CHECK_INTERVAL      60000
#define IAT_CHECK_INTERVAL      60000
#define FUNC_HASH_LENGTH 256 // how many bytes to hash from start of function
#define EVP_MAX_MD_SIZE 64
#define DLL_NAME "hook.dll"

#define HEARTBEAT_PIPE_NAME "\\\\.\\pipe\\vgrd_hb"
#define TELEMETRY_PIPE_NAME "\\\\.\\pipe\\vgrd_tm"
#define COMMANDS_PIPE_NAME "\\\\.\\pipe\\vgrd_cmd"

#include <windows.h>
#include <winbase.h>
#include <winternl.h>
#include <ntdef.h>
#include <openssl/evp.h>

typedef struct {
    LPCSTR funcName;
    LPCSTR moduleName;
    LPVOID moduleBase;
    FARPROC originalFunc;
    FARPROC handler;
    unsigned char funcHash[SHA256_DIGEST_LENGTH];
} HookEntry;

typedef struct {
    LPCSTR name;
    LPVOID base;
    unsigned char textHash[EVP_MAX_MD_SIZE];
} Module;

extern HANDLE hHeartbeat;
extern HANDLE hTelemetry;
extern HANDLE hCommands;
extern HookEntry HookList[];
extern Module TrackedModules[];
extern const size_t HookListSize;
extern const size_t NumTrackedModules;

typedef struct {
    DWORD pid;
    char  command[64];
    char  arg[64];
} COMMAND;

typedef struct {
    DWORD pid;
    char  Heartbeat[64];
} HEARTBEAT;

typedef enum {
    TM_TYPE_EMPTY_VALUE    = 0, // so agent does not parse empty values
    TM_TYPE_API_CALL       = 1,
    TM_TYPE_FILE_EVENT     = 2,
    TM_TYPE_REG_EVENT      = 3,
    TM_TYPE_TEXT_INTEGRITY = 4,
    TM_TYPE_IAT_INTEGRITY = 5,
    TM_TYPE_GENERIC_ALERT = 6,
} TELEMETRY_TYPE;

typedef enum {
    API_ARG_TYPE_EMPTY, // so agent does not parse empty values
    API_ARG_TYPE_DWORD,
    API_ARG_TYPE_ASTRING,
    API_ARG_TYPE_WSTRING,
    API_ARG_TYPE_BOOL,
    API_ARG_TYPE_PTR
} API_ARGTYPE;

//TODO make this dynamic too, not union
// union to describe an arg and its type (for parsing)
typedef struct {
    API_ARGTYPE type;
    union {
        DWORD   dwValue;
        char    astrValue[260];
        wchar_t wstrValue[260];
        BOOL    boolValue;
        PVOID   ptrValue;
    } arg;
} API_ARG;

// api call telemetry packets' first part after header
typedef struct {
    DWORD    tid;
    char     dllName[60];
    char     funcName[60];
    DWORD    argCount;
} API_CALL_HEADER;

// file system action types
typedef enum {
    FILE_ACTION_CREATE,
    FILE_ACTION_MODIFY,
    FILE_ACTION_REMOVE,
    FILE_ACTION_MOVE,
} FILE_ACTION;

// file system events' telemetry packet (etw)
typedef struct {
    char path[260];
    FILE_ACTION action;
} FILE_EVENT;

// registry events' telemetry packet (etw)
typedef struct {
    char path[260];
    char value[260];
} REG_EVENT;

// text integrity checks' telemetry packet
typedef struct {
    BOOL result;
    char module[260];
} TEXT_CHECK;

//TODO change this shit lmaoo, dont list so many damn matches especially with strings. makes it 67kB
typedef struct {
    size_t mismatchCount;
    char mismatches[260][260];
} FUNC_CHECK;

typedef struct {
    DWORD  pid;
    DWORD  type;
    size_t  dataSize;
    time_t timeStamp;
} TELEMETRY_HEADER;

typedef struct {
    char funcName[64];
    LPVOID address; // this is the invalid address IAT is pointing to
} IAT_MISMATCH;

typedef struct {
    size_t descSize;
    char* description;
} GENERIC_ALERT;

//? instead of using an union, be more memory efficient and send only what you need
//? in a different struct which you can just memcpy() into a buffer after the header
/*
typedef struct {
    TELEMETRY_HEADER header; //24B
    union {
        API_CALL   apiCall;
        FILE_EVENT fileEvent;
        REG_EVENT  regEvent;
        TEXT_CHECK textCheck;
        FUNC_CHECK funcCheck;
    } data;
} TELEMETRY;
*/
// utils.c
//void GetHookIntegrityTelemetryPacket(TELEMETRY*, int*, int);
//void GetHookBaseTelemetryPacket(TELEMETRY*, LPCSTR, LPCSTR);
//void GetTextTelemetryPacket(TELEMETRY*, char*, BOOL);
//void FillEmptyArgs(TELEMETRY*, int);
PIMAGE_IMPORT_DESCRIPTOR GetIatImportDescriptor(LPVOID);
size_t GetTelemetryPacketSize(DWORD, size_t);
TELEMETRY_HEADER GetTelemetryHeader(DWORD, size_t);
API_CALL_HEADER GetApiCallHeader(LPCSTR, LPCSTR, size_t);
TEXT_CHECK GetTextIntegrityPacket(LPCSTR, BOOL);
BYTE* GetGenericAlertPacket(LPCSTR);
void SendDllInjectionAlert();

HANDLE InitializeComms();           // ipc.c
void WaiterThread(); // ipc.c
int FillFunctionHash(unsigned char*, LPVOID, size_t);     // utils.c
int InitializeHookList();           // iathook.c
int InitializeIatHooksByHookList(); // iathook.c
void InitializeModuleList(); // iathook.c

// tampering.c
void heartbeat(HANDLE);
//int* CheckHookIntegrity(int*);
BOOL CheckTextSectionIntegrity(unsigned char*, HMODULE);
void HashTextSection(HMODULE, unsigned char*, unsigned int*);
//void PerformIntegrityChecks(HMODULE, HMODULE, HMODULE);
void CheckIatIntegrity(LPVOID);

// utils.cpp
#ifdef __cplusplus
extern "C" {
#endif
void InitializeHookMap();
HookEntry* FindHookEntry(LPCSTR);
#ifdef __cplusplus
}
#endif

//*=============================[ API hooks ]========================================

//? this is the index into HookList; the enums must be in correct order
typedef enum {
    HOOK_MESSAGE_BOX_A,
    HOOK_VIRTUAL_PROTECT,
    HOOK_VIRTUAL_PROTECT_EX,
    HOOK_NT_PROTECT_VM,
    HOOK_VIRTUAL_ALLOC,
    HOOK_VIRTUAL_ALLOC2,
    HOOK_VIRTUAL_ALLOC_EX,
    HOOK_NT_ALLOC_VM,
    HOOK_NT_ALLOC_VM_EX,
    HOOK_OPEN_PROCESS,
    HOOK_NT_OPEN_PROCESS,
    HOOK_OPEN_THREAD,
    HOOK_NT_OPEN_THREAD,
    HOOK_CREATE_PROCESS_A,
    HOOK_CREATE_PROCESS_W,
    HOOK_CREATE_PROCESS_AS_USER_A,
    HOOK_CREATE_PROCESS_AS_USER_W,
    HOOK_NT_CREATE_PROCESS,
    HOOK_NT_CREATE_PROCESS_EX,
    HOOK_NT_CREATE_USER_PROCESS,
    HOOK_CREATE_THREAD
    HOOK_CREATE_REMOTE_THREAD,
    HOOK_CREATE_REMOTE_THREAD_EX,
    HOOK_NT_CREATE_THREAD,
    HOOK_NT_CREATE_THREAD_EX,
    HOOK_CREATE_FIBER,
    HOOK_LOAD_LIBRARY_A,
    HOOK_LOAD_LIBRARY_W,
    HOOK_LOAD_LIBRARY_EX_A,
    HOOK_LOAD_LIBRARY_EX_W,
    HOOK_LDR_LOAD_DLL
    HOOK_GET_MODULE_HANDLE_A,
    HOOK_GET_MODULE_HANDLE_W,
    HOOK_GET_MODULE_HANDLE_EX_A,
    HOOK_GET_MODULE_HANDLE_EX_W,
    HOOK_GET_PROC_ADDRESS,
    HOOK_SET_DEFAULT_DLL_DIRS,
    HOOK_GET_THREAD_CONTEXT,
    HOOK_NT_GET_CONTEXT_THREAD,
    HOOK_SET_THREAD_CONTEXT,
    HOOK_NT_SET_CONTEXT_THREAD,
    HOOK_SUSPEND_THREAD,
    HOOK_RESUME_THREAD,
    HOOK_NT_SUSPEND_THREAD,
    HOOK_NT_RESUME_THREAD,
    HOOK_TERMINATE_THREAD,
    HOOK_NT_TERMINATE_THREAD,
    HOOK_TERMINATE_PROCESS,
    HOOK_NT_TERMINATE_PROCESS,
    HOOK_NT_SUSPEND_PROCESS,
    HOOK_NT_RESUME_PROCESS,
    HOOK_QUEUE_USER_APC,
    HOOK_QUEUE_USER_APC2,
    HOOK_NT_QUEUE_APC_THREAD,
    HOOK_NT_QUEUE_APC_THREAD_EX,
    HOOK_NT_QUEUE_APC_THREAD_EX2,
    HOOK_ADJUST_TOKEN_PRIVILEGES,
    HOOK_WAIT_FOR_SINGLE_OBJECT,
    HOOK_WAIT_FOR_SINGLE_OBJECT_EX,
    HOOK_WAIT_FOR_MULTIPLE_OBJECTS,
    HOOK_WAIT_FOR_MULTIPLE_OBJECTS_EX,
    HOOK_MSG_WAIT_FOR_MULTIPLE_OBJECTS,
    HOOK_MSG_WAIT_FOR_MULTIPLE_OBJECTS_EX,
    HOOK_SIGNAL_OBJECT_AND_WAIT,
    HOOK_SLEEP_EX,
    HOOK_WAIT_ON_ADDRESS,
    HOOK_SET_WINDOWS_HOOK_EX_A,
    HOOK_SET_WINDOWS_HOOK_EX_W,
    HOOK_SET_WIN_EVENT_HOOK,
    HOOK_SHELL_EXECUTE_A,
    HOOK_SHELL_EXECUTE_W,
    HOOK_SHELL_EXECUTE_EX_A,
    HOOK_SHELL_EXECUTE_EX_W,
    HOOK_OPEN_THREAD_TOKEN,
    HOOK_NT_OPEN_THREAD_TOKEN,
    HOOK_NT_OPEN_THREAD_TOKEN_EX,
    HOOK_OPEN_PROCESS_TOKEN,
    HOOK_NT_OPEN_PROCESS_TOKEN,
    HOOK_NT_OPEN_PROCESS_TOKEN_EX,
    HOOK_DUPLICATE_TOKEN,
    HOOK_DUPLICATE_TOKEN_EX,
    HOOK_NT_DUPLICATE_TOKEN,
    HOOK_DUPLICATE_HANDLE,
    HOOK_NT_DUPLICATE_OBJECT,
    HOOK_CREATE_TH32_SNAPSHOT,
    HOOK_FIND_WINDOW_A,
    HOOK_FIND_WINDOW_W,
    HOOK_FIND_WINDOW_EX_A,
    HOOK_FIND_WINDOW_EX_W,
    HOOK_NT_USER_FIND_WINDOW_EX,
    HOOK_ADD_VEH,
    HOOK_RTL_ADD_VEH,
    HOOK_NT_QUERY_SYSTEM_INFORMATION,
    HOOK_NT_QUERY_SYSTEM_INFORMATION_EX,
    HOOK_NT_QUERY_INFORMATION_THREAD,
    HOOK_NT_QUERY_INFORMATION_PROCESS,
    HOOK_CREATE_FILE_MAPPING_A,
    HOOK_CREATE_FILE_MAPPING_W,
    HOOK_CREATE_FILE_MAPPING_2,
    HOOK_CREATE_FILE_MAPPING_NUMA_A,
    HOOK_CREATE_FILE_MAPPING_NUMA_W,
    HOOK_NT_CREATE_SECTION,
    HOOK_NT_CREATE_SECTION_EX,
    HOOK_READ_PROCESS_MEMORY,
    HOOK_NT_READ_VIRTUAL_MEMORY,
    HOOK_NT_READ_VIRTUAL_MEMORY_EX,
    HOOK_WRITE_PROCESS_MEMORY,
    HOOK_NT_WRITE_VIRTUAL_MEMORY,
    HOOK_GET_THREAD_DESCRIPTION,
    HOOK_SET_THREAD_DESCRIPTION,
    HOOK_SET_THREAD_EXECUTION_STATE,
    HOOK_NT_SET_THREAD_EXECUTION_STATE,
    HOOK_THREAD_32_FIRST,
    HOOK_THREAD_32_NEXT,
    HOOK_PROCESS_32_FIRST_A,
    HOOK_PROCESS_32_NEXT_A,
    HOOK_PROCESS_32_FIRST_W,
    HOOK_PROCESS_32_NEXT_W,
    HOOK_MODULE_32_FIRST_A,
    HOOK_MODULE_32_NEXT_A,
    HOOK_MODULE_32_FIRST_W,
    HOOK_MODULE_32_NEXT_W,
    HOOK_IS_DEBUGGER_PRESENT,
    HOOK_WIN_EXEC,

/*
    HOOK_CRYPT_CREATE_HASH,
    HOOK_CRYPT_ENCRYPT,
    HOOK_ENCRYPT_FILE_A,
    HOOK_ENCRYPT_FILE_W,*/
} HOOK_INDEX;

//? These are for calling hooked api functions from address in the hook handler function
//* user32.dll!MessageBoxA
typedef int (WINAPI *MESSAGEBOXA)(HWND, LPCSTR, LPCSTR, UINT);
int MessageBoxA_Handler(HWND, LPCSTR, LPCSTR, UINT);

//* kernel32.dll!VirtualProtect
typedef BOOL (WINAPI *VIRTUALPROTECT)(LPVOID, SIZE_T, DWORD, PDWORD);
BOOL VirtualProtect_Handler(LPVOID, SIZE_T, DWORD, PDWORD);
//* kernel32.dll!VirtualProtectEx
typedef BOOL (WINAPI *VIRTUALPROTECTEX)(HANDLE, LPVOID, SIZE_T, DWORD, PDWORD);
BOOL VirtualProtectEx_Handler(HANDLE, LPVOID, SIZE_T, DWORD, PDWORD);
//* ntdll!NtProtectVirtualMemory
typedef NTSTATUS (NTAPI *NTPROTECTVM)(HANDLE, PVOID, PSIZE_T, ULONG, PULONG);
NTSTATUS NtProtectVM_Handler(HANDLE, PVOID*, PSIZE_T, ULONG, PULONG);

//* kernel32.dll!VirtualAlloc
typedef LPVOID (WINAPI *VIRTUALALLOC)(LPVOID, SIZE_T, DWORD, DWORD);
LPVOID VirtualAlloc_Handler(LPVOID, SIZE_T, DWORD, DWORD);
//* kernel32.dll!VirtualAllocEx
typedef LPVOID (WINAPI *VIRTUALALLOCEX)(HANDLE, LPVOID, SIZE_T, DWORD, DWORD);
LPVOID VirtualAllocEx_Handler(HANDLE, LPVOID, SIZE_T, DWORD, DWORD);
//* kernelbase.dll!VirtualAlloc2
typedef LPVOID (WINAPI *VIRTUALALLOC2)(HANDLE, PVOID, SIZE_T, ULONG, ULONG, MEM_EXTENDED_PARAMETER*, ULONG);
PVOID VirtualAlloc2_Handler(HANDLE, PVOID, SIZE_T, ULONG, ULONG, MEM_EXTENDED_PARAMETER*, ULONG);
//* ntdll.dll!NtAllocateVirtualMemory
typedef NTSTATUS (NTAPI *NTALLOCVM)(HANDLE, PVOID*, ULONG_PTR, PSIZE_T, ULONG, ULONG);
NTSTATUS NtAllocateVM_Handler(HANDLE, PVOID*, ULONG_PTR, PSIZE_T, ULONG, ULONG);
//* ntdll.dll!NtAllocateVirtualMemoryEx
typedef NTSTATUS (NTAPI *NTALLOCVMEX)(HANDLE, PVOID*, PSIZE_T, ULONG, ULONG, PMEM_EXTENDED_PARAMETER, ULONG);
NTSTATUS NtAllocateVMEx_Handler(HANDLE, PVOID*, PSIZE_T, ULONG, ULONG, PMEM_EXTENDED_PARAMETER, ULONG);

//* kernel32.dll!OpenProcess
typedef HANDLE (WINAPI *OPENPROCESS)(DWORD, BOOL, DWORD);
HANDLE OpenProcess_Handler(DWORD, BOOL, DWORD);
//* ntdll.dll!NtOpenProcess
typedef NTSTATUS (NTAPI *NTOPENPROCESS)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PCLIENT_ID);
NTSTATUS NtOpenProcess_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PCLIENT_ID);
//* kernel32.dll!OpenThread
typedef HANDLE (WINAPI *OPENTHREAD)(DWORD, BOOL, DWORD);
HANDLE OpenThread_Handler(DWORD, BOOL, DWORD);
//* ntdll.dll!NtOpenThread
typedef NTSTATUS (NTAPI *NTOPENTHREAD)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PCLIENT_ID);
NTSTATUS NtOpenThread_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PCLIENT_ID);

//* kernel32.dll!CreateProcessA
typedef BOOL (WINAPI *CREATEPROCESSA)(LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES,
  BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
BOOL CreateProcessA_Handler(LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES,
  BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
//* kernel32.dll!CreateProcessW
typedef BOOL (WINAPI *CREATEPROCESSW)(LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES,
  BOOL, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
BOOL CreateProcessW_Handler(LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES,
  BOOL, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
//* kernel32.dll!CreateProcessAsUserA
typedef BOOL (WINAPI *CREATEPROCESSASUSERA)(HANDLE, LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES,
LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
BOOL CreateProcessAsUserA_Handler(HANDLE, LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES,
    LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
//* kernel32.dll!CreateProcessAsUserW
typedef BOOL (WINAPI *CREATEPROCESSASUSERW)(HANDLE, LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES,
LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
BOOL CreateProcessAsUserW_Handler(HANDLE, LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES,
    LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION);
//* ntdll.dll!NtCreateProcess
typedef NTSTATUS (NTAPI* NTCREATEPROCESS)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE,
BOOLEAN, HANDLE, HANDLE, HANDLE);
NTSTATUS NtCreateProcess_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, BOOLEAN, HANDLE, HANDLE, HANDLE);
//* ntdll.dll!NtCreateProcessEx
typedef NTSTATUS (NTAPI* NTCREATEPROCESSEX)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE,
ULONG, HANDLE, HANDLE, HANDLE, ULONG);
NTSTATUS NtCreateProcessEx_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, ULONG, HANDLE, HANDLE, HANDLE, ULONG);
//* ntdll.dll!NtCreateUserProcess
typedef NTSTATUS (NTAPI* NTCREATEUSERPROCESS)(PHANDLE, PHANDLE, ACCESS_MASK, ACCESS_MASK, PCOBJECT_ATTRIBUTES,
PCOBJECT_ATTRIBUTES, ULONG, ULONG, void*, void*, void*);
NTSTATUS NtCreateUserProcess_Handler(PHANDLE, PHANDLE, ACCESS_MASK, ACCESS_MASK, PCOBJECT_ATTRIBUTES,
    PCOBJECT_ATTRIBUTES, ULONG, ULONG, void*, void*, void*);

//* kernel32.dll!CreateThread
typedef HANDLE (WINAPI *CREATETHREAD)(LPSECURITY_ATTRIBUTES, SIZE_T,
LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
HANDLE CreateThread_Handler(LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
//* kernel32.dll!CreateRemoteThread
typedef HANDLE (WINAPI *CREATEREMOTETHREAD)(HANDLE, LPSECURITY_ATTRIBUTES, SIZE_T,
LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
HANDLE CreateRemoteThread_Handler(HANDLE, LPSECURITY_ATTRIBUTES, SIZE_T,
LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
//* kernel32.dll!CreateRemoteThreadEx
typedef HANDLE (WINAPI *CREATEREMOTETHREADEX)(HANDLE, LPSECURITY_ATTRIBUTES, SIZE_T,
LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPPROC_THREAD_ATTRIBUTE_LIST, LPDWORD);
HANDLE CreateRemoteThreadEx_Handler(HANDLE, LPSECURITY_ATTRIBUTES, SIZE_T,
LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPPROC_THREAD_ATTRIBUTE_LIST, LPDWORD);
//* ntdll.dll!NtCreateThread
typedef NTSTATUS (NTAPI *NTCREATETHREAD)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, PCLIENT_ID, PCONTEXT, void*, BOOL);
NTSTATUS NtCreateThread_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, PCLIENT_ID, PCONTEXT, void*, BOOL);
//* ntdll.dll!NtCreateThreadEx
typedef NTSTATUS (NTAPI *NTCREATETHREADEX)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, void*, PVOID, ULONG, SIZE_T, SIZE_T, SIZE_T, void*);
NTSTATUS NtCreateThreadEx_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, HANDLE, void*, PVOID, ULONG, SIZE_T, SIZE_T, SIZE_T, void*);
//* kernel32!CreateFiber
typedef LPVOID (WINAPI *CREATEFIBER)(SIZE_T, LPFIBER_START_ROUTINE, LPVOID);
LPVOID CreateFiber_Handler(SIZE_T, LPFIBER_START_ROUTINE, LPVOID);

//* kernel32.dll!LoadLibraryA
typedef HMODULE (WINAPI *LOADLIBRARYA)(LPCSTR);
HMODULE LoadLibraryA_Handler(LPCSTR);
//* kernel32.dll!LoadLibraryW
typedef HMODULE (WINAPI *LOADLIBRARYW)(LPCWSTR);
HMODULE LoadLibraryW_Handler(LPCWSTR);
//* kernel32.dll!LoadLibraryExA
typedef HMODULE (WINAPI *LOADLIBRARYEXA)(LPCSTR, HANDLE, DWORD);
HMODULE LoadLibraryExA_Handler(LPCSTR, HANDLE, DWORD);
//* kernel32.dll!LoadLibraryExW
typedef HMODULE (WINAPI *LOADLIBRARYEXW)(LPCWSTR, HANDLE, DWORD);
HMODULE LoadLibraryExW_Handler(LPCWSTR, HANDLE, DWORD);
//* ntdll.dll!LdrLoadDll
typedef NTSTATUS (NTAPI *LDRLOADDLL)(PCWSTR, PULONG, PCUNICODE_STRING, PVOID);
NTSTATUS LdrLoadDll_Handler(PCWSTR, PULONG, PCUNICODE_STRING, PVOID);

//* kernel32.dll!GetModuleHandleA
typedef HMODULE (WINAPI *GETMODULEHANDLEA)(LPCSTR);
HMODULE GetModuleHandleA_Handler(LPCSTR);
//* kernel32.dll!GetModuleHandleW
typedef HMODULE (WINAPI *GETMODULEHANDLEW)(LPCWSTR);
HMODULE GetModuleHandleW_Handler(LPCWSTR);
//* kernel32.dll!GetModuleHandleExA
typedef BOOL (WINAPI *GETMODULEHANDLEEXA)(DWORD, LPCSTR, HMODULE*);
BOOL GetModuleHandleExA_Handler(DWORD, LPCSTR, HMODULE*);
//* kernel32.dll!GetModuleHandleExW
typedef BOOL (WINAPI *GETMODULEHANDLEEXW)(DWORD, LPCWSTR, HMODULE*);
BOOL GetModuleHandleExW_Handler(DWORD, LPCWSTR, HMODULE*);
//* kernel32.dll!GetProcAddress
typedef FARPROC (WINAPI *GETPROCADDRESS)(HMODULE, LPCSTR);
FARPROC GetProcAddress_Handler(HMODULE, LPCSTR);

//* kernel32.dll!SetDefaultDllDirectories
typedef FARPROC (WINAPI* SETDEFAULTDLLDIRS)(DWORD);
FARPROC SetDefaultDllDirectories_Handler(DWORD);


//* kernel32.dll!GetThreadContext
typedef BOOL (WINAPI *GETTHREADCONTEXT)(HANDLE, LPCONTEXT);
BOOL GetThreadContext_Handler(HANDLE, LPCONTEXT);
//* ntdll.dll!NtGetContextThread
typedef NTSTATUS (NTAPI* NTGETCONTEXTTHREAD)(HANDLE, PCONTEXT);
NTSTATUS NtGetContextThread_Handler(HANDLE, PCONTEXT);
//* kernel32.dll!SetThreadContext
typedef BOOL (WINAPI *SETTHREADCONTEXT)(HANDLE, const CONTEXT);
BOOL SetThreadContext_Handler(HANDLE, const CONTEXT);
//* ntdll.dll!NtSetContextThread
typedef NTSTATUS (NTAPI* NTSETCONTEXTTHREAD)(HANDLE, PCONTEXT);
NTSTATUS NtSetContextThread_Handler(HANDLE, PCONTEXT);

//* kernel32.dll!SuspendThread
typedef DWORD (WINAPI *SUSPENDTHREAD)(HANDLE);
DWORD SuspendThread_Handler(HANDLE);
//* kernel32.dll!ResumeThread
typedef DWORD (WINAPI *RESUMETHREAD)(HANDLE);
DWORD ResumeThread_Handler(HANDLE);
//* ntdll.dll!NtSuspendThread
typedef NTSTATUS (NTAPI* NTSUSPENDTHREAD)(HANDLE, PULONG);
NTSTATUS NtSuspendThread_Handler(HANDLE, PULONG);
//* ntdll.dll!NtResumeThread
typedef NTSTATUS (NTAPI* NTRESUMETHREAD)(HANDLE, PULONG);
NTSTATUS NtResumeThread_Handler(HANDLE, PULONG);
//* kernel32.dll!TerminateThread
typedef BOOL (WINAPI* TERMINATETHREAD)(HANDLE, DWORD);
BOOL TerminateThread_Handler(HANDLE, DWORD);
//* ntdll.dll!NtTerminateThread
typedef NTSTATUS (NTAPI* NTTERMINATETHREAD)(HANDLE, NTSTATUS);
NTSTATUS NtTerminateThread_Handler(HANDLE, NTSTATUS);
//* kernel32.dll!TerminateProcess
typedef BOOL (WINAPI* TERMINATEPROCESS)(HANDLE, UINT);
BOOL TerminateProcess_Handler(HANDLE, UINT);
//* ntdll.dll!NtTerminateProcess
typedef NTSTATUS (NTAPI* NTTERMINATEPROCESS)(HANDLE, NTSTATUS);
NTSTATUS NtTerminateProcess_Handler(HANDLE, NTSTATUS);
//* ntdll.dll!NtSuspendProcess
typedef NTSTATUS (NTAPI* NTSUSPENDPROCESS)(HANDLE);
NTSTATUS NtSuspendProcess_Handler(HANDLE);
//* ntdll.dll!NtResumeProcess
typedef NTSTATUS (NTAPI* NTRESUMEPROCESS)(HANDLE);
NTSTATUS NtResumeProcess_Handler(HANDLE);

//* kernel32.dll!QueueUserAPC
typedef DWORD (WINAPI *QUEUEUSERAPC)(PAPCFUNC, HANDLE, ULONG_PTR);
DWORD QueueUserAPC_Handler(PAPCFUNC, HANDLE, ULONG_PTR);
//* kernel32.dll!QueueUserAPC2
typedef BOOL (WINAPI *QUEUEUSERAPC2)(PAPCFUNC, HANDLE, ULONG_PTR, QUEUE_USER_APC_FLAGS);
BOOL QueueUserAPC2_Handler(PAPCFUNC, HANDLE, ULONG_PTR, QUEUE_USER_APC_FLAGS);
//* ntdll.dll!NtQueueApcThread
typedef NTSTATUS (NTAPI* NTQUEUEAPCTHREAD)(HANDLE, PPS_APC_ROUTINE, PVOID, PVOID, PVOID);
NTSTATUS NtQueueApcThread_Handler(HANDLE, PPS_APC_ROUTINE, PVOID, PVOID, PVOID);
//* ntdll.dll!NtQueueApcThreadEx
typedef NTSTATUS (NTAPI* NTQUEUEAPCTHREADEX)(HANDLE, HANDLE, PPS_APC_ROUTINE, PVOID, PVOID, PVOID);
NTSTATUS NtQueueApcThreadEx_Handler(HANDLE, HANDLE, PPS_APC_ROUTINE, PVOID, PVOID, PVOID);
//* ntdll.dll!NtQueueApcThreadEx2
typedef NTSTATUS (NTAPI* NTQUEUEAPCTHREADEX2)(HANDLE, HANDLE, ULONG, PPS_APC_ROUTINE, PVOID, PVOID, PVOID);
NTSTATUS NtQueueApcThreadEx2_Handler(HANDLE, HANDLE, ULONG, PPS_APC_ROUTINE, PVOID, PVOID, PVOID);

//* kernel32.dll!WaitForSingleObject
typedef DWORD (WINAPI* WAITFORSINGLEOBJECT)(HANDLE, DWORD);
DWORD WaitForSingleObject_Handler(HANDLE, DWORD);
//* kernel32.dll!WaitForSingleObjectEx
typedef DWORD (WINAPI* WAITFORSINGLEOBJECTEX)(HANDLE, DWORD, BOOL);
DWORD WaitForSingleObjectEx_Handler(HANDLE, DWORD, BOOL);
//* kernel32.dll!WaitForMultipleObjects
typedef DWORD (WINAPI* WAITFORMULTIPLEOBJECTS)(DWORD, const HANDLE, BOOL, DWORD);
DWORD WaitForMultipleObjects_Handler(DWORD, const HANDLE, BOOL, DWORD);
//* kernel32.dll!WaitForMultipleObjectsEx
typedef DWORD (WINAPI* WAITFORMULTIPLEOBJECTSEX)(DWORD, const HANDLE, BOOL, DWORD, BOOL);
DWORD WaitForMultipleObjectsEx_Handler(DWORD, const HANDLE, BOOL, DWORD, BOOL);
//* user32.dll!MsgWaitForMultipleObjects
typedef DWORD (WINAPI* MSGWAITFORMULTIPLEOBJECTS)(DWORD, const HANDLE, BOOL, DWORD, DWORD);
DWORD MsgWaitForMultipleObjects_Handler(DWORD, const HANDLE, BOOL, DWORD, DWORD);
//* user32.dll!MsgWaitForMultipleObjectsEx
typedef DWORD (WINAPI* MSGWAITFORMULTIPLEOBJECTSEX)(DWORD, const HANDLE, DWORD, DWORD, DWORD);
DWORD MsgWaitForMultipleObjectsEx_Handler(DWORD, const HANDLE, DWORD, DWORD, DWORD);
//* kernel32.dll!SignalObjectAndWait
typedef DWORD (WINAPI* SIGNALOBJECTANDWAIT)(HANDLE, HANDLE, DWORD, BOOL);
DWORD SignalObjectAndWait_Handler(HANDLE, HANDLE, DWORD, BOOL);
//* kernel32.dll!SleepEx
typedef DWORD (WINAPI* SLEEPEX)(DWORD, BOOL);
DWORD SleepEx_Handler(DWORD, BOOL);
//* api-ms-win-core-synch-l1-2-0.dll!WaitOnAddress
typedef BOOL (WINAPI* WAITONADDRESS)(volatile VOID*, PVOID, SIZE_T, DWORD);
BOOL WaitOnAddress_Handler(volatile VOID*, PVOID, SIZE_T, DWORD);

//* user32.dll!SetWindowsHookExA
typedef HHOOK (WINAPI *SETWINDOWSHOOKEXA)(int, HOOKPROC, HINSTANCE, DWORD);
HHOOK SetWindowsHookExA_Handler(int, HOOKPROC, HINSTANCE, DWORD);
//* user32.dll!SetWindowsHookExW
typedef HHOOK (WINAPI *SETWINDOWSHOOKEXW)(int, HOOKPROC, HINSTANCE, DWORD);
HHOOK SetWindowsHookExW_Handler(int, HOOKPROC, HINSTANCE, DWORD);
//* user32.dll!SetWinEventHook
typedef HWINEVENTHOOK (WINAPI* SETWINEVENTHOOK)(DWORD, DWORD, HMODULE, WINEVENTPROC, DWORD, DWORD, DWORD);
HWINEVENTHOOK SetWinEventHook_Handler(DWORD, DWORD, HMODULE, WINEVENTPROC, DWORD, DWORD, DWORD);

//* shell32.dll!ShellExecuteA
typedef HINSTANCE (WINAPI* SHELLEXECUTEA)(HWND, LPCSTR, LPCSTR, LPCSTR, LPCSTR, INT);
HINSTANCE ShellExecuteA_Handler(HWND, LPCSTR, LPCSTR, LPCSTR, LPCSTR, INT);
//* shell32.dll!ShellExecuteW
typedef HINSTANCE (WINAPI* SHELLEXECUTEW)(HWND, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, INT);
HINSTANCE ShellExecuteW_Handler(HWND, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, INT);
//* shell32.dll!ShellExecuteExA
typedef HINSTANCE (WINAPI* SHELLEXECUTEEXA)(SHELLEXECUTEINFOA*);
HINSTANCE ShellExecuteExA_Handler(SHELLEXECUTEINFOA*);
//* shell32.dll!ShellExecuteExW
typedef HINSTANCE (WINAPI* SHELLEXECUTEEXW)(SHELLEXECUTEINFOW*);
HINSTANCE ShellExecuteExW_Handler(SHELLEXECUTEINFOW*);

//* kernel32.dll!OpenThreadToken
typedef BOOL (WINAPI *OPENTHREADTOKEN)(HANDLE, DWORD, BOOL, PHANDLE);
BOOL OpenThreadToken_Handler(HANDLE, DWORD, BOOL, PHANDLE);
//* ntdll.dll!NtOpenThreadToken
typedef NTSTATUS (NTAPI* NTOPENTHREADTOKEN)(HANDLE, ACCESS_MASK, BOOLEAN, PHANDLE);
NTSTATUS NtOpenThreadToken_Handler(HANDLE, ACCESS_MASK, BOOLEAN, PHANDLE);
//* ntdll.dll!NtOpenThreadTokenEx
typedef NTSTATUS (NTAPI* NTOPENTHREADTOKENEX)(HANDLE, ACCESS_MASK, BOOLEAN, ULONG, PHANDLE);
NTSTATUS NtOpenThreadTokenEx_Handler(HANDLE, ACCESS_MASK, BOOLEAN, ULONG, PHANDLE);
//* kernel32.dll!OpenProcessToken
typedef BOOL (WINAPI *OPENPROCESSTOKEN)(HANDLE, DWORD, PHANDLE);
BOOL OpenProcessToken_Handler(HANDLE, DWORD, PHANDLE);
//* ntdll.dll!NtOpenProcessToken
typedef NTSTATUS (NTAPI* NTOPENPROCESSTOKEN)(HANDLE, ACCESS_MASK, PHANDLE);
NTSTATUS NtOpenProcessToken_Handler(HANDLE, ACCESS_MASK, PHANDLE);
//* ntdll.dll!NtOpenProcessTokenEx
typedef NTSTATUS (NTAPI* NTOPENPROCESSTOKENEX)(HANDLE, ACCESS_MASK, ULONG, PHANDLE);
NTSTATUS NtOpenProcessTokenEx_Handler(HANDLE, ACCESS_MASK, ULONG, PHANDLE);
//* kernel32.dll!AdjustTokenPrivileges
typedef BOOL (WINAPI* ADJUSTTOKENPRIVILEGES)(HANDLE, BOOL, PTOKEN_PRIVILEGES, DWORD, PTOKEN_PRIVILEGES, PDWORD);
BOOL AdjustTokenPrivileges_Handler(HANDLE, BOOL, PTOKEN_PRIVILEGES, DWORD, PTOKEN_PRIVILEGES, PDWORD);

//* kernel32.dll!DuplicateToken
typedef BOOL (WINAPI* DUPLICATETOKEN)(HANDLE, SECURITY_IMPERSONATION_LEVEL, PHANDLE);
BOOL DuplicateToken_Handler(HANDLE, SECURITY_IMPERSONATION_LEVEL, PHANDLE);
//* kernel32.dll!DuplicateTokenEx
typedef BOOL (WINAPI* DUPLICATETOKENEX)(HANDLE, DWORD, LPSECURITY_ATTRIBUTES, SECURITY_IMPERSONATION_LEVEL, TOKEN_TYPE, PHANDLE);
BOOL DuplicateTokenEx_Handler(HANDLE, DWORD, LPSECURITY_ATTRIBUTES, SECURITY_IMPERSONATION_LEVEL, TOKEN_TYPE, PHANDLE);
//* ntdll.dll!NtDuplicateToken
typedef NTSTATUS (NTAPI* NTDUPLICATETOKEN)(HANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, BOOLEAN, TOKEN_TYPE, PHANDLE);
NTSTATUS NtDuplicateObject_Handler(HANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, BOOLEAN, TOKEN_TYPE, PHANDLE);
//* kernel32.dll!DuplicateHandle
typedef BOOL (WINAPI* DUPLICATEHANDLE)(HANDLE, HANDLE, HANDLE, LPHANDLE, DWORD, BOOL, DWORD);
BOOL DuplicateHandle_Handler(HANDLE, HANDLE, HANDLE, LPHANDLE, DWORD, BOOL, DWORD);
//* ntdll.dll!NtDuplicateObject
typedef NTSTATUS (NTAPI* NTDUPLICATEOBJECT)(HANDLE, HANDLE, HANDLE, PHANDLE, ACCESS_MASK, ULONG, ULONG);
NTSTATUS NtDuplicateObject_Handler(HANDLE, HANDLE, HANDLE, PHANDLE, ACCESS_MASK, ULONG, ULONG);

//* kernel32.dll!CreateToolhelp32Snapshot
typedef HANDLE (WINAPI* CREATETH32SNAPSHOT)(DWORD, DWORD);
HANDLE CreateToolhelp32Snapshot_Handler(DWORD, DWORD);
//* user32.dll!FindWindowA
typedef HANDLE (WINAPI* FINDWINDOWA)(LPCSTR, LPCSTR);
HWND FindWindowA_Handler(LPCSTR, LPCSTR);
//* user32.dll!FindWindowW
typedef HANDLE (WINAPI* FINDWINDOWW)(LPCWSTR, LPCWSTR);
HWND FindWindowW_Handler(LPCWSTR, LPCWSTR);
//* user32.dll!FindWindowExA
typedef HANDLE (WINAPI* FINDWINDOWEXA)(HWND, HWND, LPCSTR, LPCSTR);
HWND FindWindowExA_Handler(HWND, HWND, LPCSTR, LPCSTR);
//* user32.dll!FindWindowExW
typedef HANDLE (WINAPI* FINDWINDOWEXW)(HWND, HWND, LPCWSTR, LPCWSTR);
HWND FindWindowExW_Handler(HWND, HWND, LPCWSTR, LPCWSTR);
//* ntdll.dll!NtUserFindWindowEx
typedef NTSTATUS (NTAPI* NTUSERFINDWINDOWEX)(HWND, HWND, PCUNICODE_STRING, PCUNICODE_STRING, ULONG);
NTSTATUS NtUserFindWindowEx_Handler(HWND, HWND, PCUNICODE_STRING, PCUNICODE_STRING, ULONG);

//* kernel32.dll!AddVectoredExceptionHandler
typedef PVOID (WINAPI* ADDVEH)(ULONG, PVECTORED_EXCEPTION_HANDLER);
PVOID AddVeh_Handler(ULONG, PVECTORED_EXCEPTION_HANDLER)
//* ntdll.dll!RtlAddVectoredExceptionHandler
typedef NTSTATUS (NTAPI* RTLADDVEH)(ULONG, PVECTORED_EXCEPTION_HANDLER);
NTSTATUS RtlAddVeh_Handler(ULONG, PVECTORED_EXCEPTION_HANDLER);

//* ntdll.dll!NtQuerySystemInformation
typedef NTSTATUS (NTAPI* NTQUERYSYSTEMINFORMATION)(SYSTEM_INFORMATION_CLASS, PVOID, ULONG, PULONG);
NTSTATUS NtQuerySystemInformation_Handler(SYSTEM_INFORMATION_CLASS, PVOID, ULONG, PULONG);
//* ntdll.dll!NtQuerySystemInformationEx
typedef NTSTATUS (NTAPI* NTQUERYSYSTEMINFORMATIONEX)(SYSTEM_INFORMATION_CLASS, PVOID, ULONG, PVOID, ULONG, PULONG);
NTSTATUS NtQuerySystemInformationEx_Handler(SYSTEM_INFORMATION_CLASS, PVOID, ULONG, PVOID, ULONG, PULONG);
//* ntdll.dll!NtQueryInformationThread
typedef NTSTATUS (NTAPI* NTQUERYINFORMATIONTHREAD)(HANDLE, THREADINFOCLASS, PVOID, ULONG, PULONG);
NTSTATUS NtQueryInformationThread_Handler(HANDLE, THREADINFOCLASS, PVOID, ULONG, PULONG);
//* ntdll.dll!NtQueryInformationProcess
typedef NTSTATUS (NTAPI* NTQUERYINFORMATIONPROCESS)(HANDLE, PROCESSINFOCLASS, PVOID, ULONG, PULONG);
NTSTATUS NtQueryInformationProcess_Handler(HANDLE, PROCESSINFOCLASS, PVOID, ULONG, PULONG);

//* kernel32.dll!CreateFileMappingA
typedef HANDLE (WINAPI* CREATEFILEMAPPINGA)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR);
HANDLE CreateFileMappingA_Handler(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR);
//* kernel32.dll!CreateFileMappingW
typedef HANDLE (WINAPI* CREATEFILEMAPPINGW)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR);
HANDLE CreateFileMappingW_Handler(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR);
//* kernel32.dll!CreateFileMapping2
typedef HANDLE (WINAPI* CREATEFILEMAPPING2)(HANDLE, SECURITY_ATTRIBUTES*, ULONG, ULONG, ULONG, ULONG64, PCWSTR, MEM_EXTENDED_PARAMETER*, ULONG);
HANDLE CreateFileMapping2_Handler(HANDLE, SECURITY_ATTRIBUTES*, ULONG, ULONG, ULONG, ULONG64, PCWSTR, MEM_EXTENDED_PARAMETER*, ULONG);
//* kernel32.dll!CreateFileMappingNumaA
typedef HANDLE (WINAPI* CREATEFILEMAPPINGNUMAA)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR, DWORD);
HANDLE CreateFileMappingNumaA_Handler(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR, DWORD);
//* kernel32.dll!CreateFileMappingNumaW
typedef HANDLE (WINAPI* CREATEFILEMAPPINGNUMAW)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR, DWORD);
HANDLE CreateFileMappingNumaW_Handler(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR, DWORD);
//* ntdll.dll!NtCreateSection
typedef NTSTATUS (NTAPI* NTCREATESECTION)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PLARGE_INTEGER, ULONG, ULONG, HANDLE);
NTSTATUS NtCreateSection_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PLARGE_INTEGER, ULONG, ULONG, HANDLE);
//* ntdll.dll!NtCreateSectionEx
typedef NTSTATUS (NTAPI* NTCREATESECTIONEX)(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PLARGE_INTEGER, ULONG, ULONG, HANDLE, PMEM_EXTENDED_PARAMETER, ULONG);
NTSTATUS NtCreateSection_Handler(PHANDLE, ACCESS_MASK, PCOBJECT_ATTRIBUTES, PLARGE_INTEGER, ULONG, ULONG, HANDLE, PMEM_EXTENDED_PARAMETER, ULONG);

//* kernel32.dll!ReadProcessMemory
typedef BOOL (WINAPI* READPROCESSMEMORY)(HANDLE, LPCVOID, LPVOID, SIZE_T, SIZE_T*);
BOOL ReadProcessMemory_Handler(HANDLE, LPCVOID, LPVOID, SIZE_T, SIZE_T*);
//* ntdll.dll!NtReadVirtualMemory
typedef NTSTATUS (NTAPI* NTREADVIRTUALMEMORY)(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T);
NTSTATUS NtReadVirtualMemory_Handler(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T);
//* ntdll.dll!NtReadVirtualMemoryEx
typedef NTSTATUS (NTAPI* NTREADVIRTUALMEMORYEX)(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T, ULONG);
NTSTATUS NtReadVirtualMemoryEx_Handler(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T, ULONG);
//* kernel32.dll!WriteProcessMemory
typedef BOOL (WINAPI* WRITEPROCESSMEMORY)(HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T*);
BOOL WriteProcessMemory_Handler(HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T*);
//* ntdll.dll!NtWriteVirtualMemory
typedef NTSTATUS (NTAPI* NTWRITEVIRTUALMEMORY)(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T);
NTSTATUS NtWriteVirtualMemory_Handler(HANDLE, PVOID, PVOID, SIZE_T, PSIZE_T);

//* kernel32.dll!GetThreadDescription
typedef HRESULT (WINAPI* GETTHREADDESCRIPTION)(HANDLE, PWSTR*);
HRESULT GetThreadDescription_Handler(HANDLE, PWSTR*);
//* kernel32.dll!SetThreadDescription
typedef HRESULT (WINAPI* SETTHREADDESCRIPTION)(HANDLE, PCWSTR);
HRESULT GetThreadDescription_Handler(HANDLE, PCWSTR);
//* kernel32.dll!SetThreadExecutionState
typedef EXECUTION_STATE (WINAPI* SETTHREADEXECUTIONSTATE)(EXECUTION_STATE);
EXECUTION_STATE SetThreadExecutionState_Handler(EXECUTION_STATE);
//* ntdll.dll!NtSetThreadExecutionState
typedef NTSTATUS (NTAPI* NTSETTHREADEXECUTIONSTATE)(EXECUTION_STATE, EXECUTION_STATE*);
NTSTATUS NtSetThreadExecutionState_Handler(EXECUTION_STATE, EXECUTION_STATE*);

//* kernel32.dll!Thread32First
typedef BOOL (WINAPI* THREAD32FIRST)(HANDLE, LPTHREADENTRY32);
BOOL Thread32First_Handler(HANDLE, LPTHREADENTRY32);
//* kernel32.dll!Thread32Next
typedef BOOL (WINAPI* THREAD32NEXT)(HANDLE, LPTHREADENTRY32);
BOOL Thread32Next_Handler(HANDLE, LPTHREADENTRY32);
//* kernel32.dll!Process32First
typedef BOOL (WINAPI* PROCESS32FIRST)(HANDLE, LPPROCESSENTRY32);
BOOL Process32First_Handler(HANDLE, LPPROCESSENTRY32);
//* kernel32.dll!Process32Next
typedef BOOL (WINAPI* PROCESS32NEXT)(HANDLE, LPPROCESSENTRY32);
BOOL Process32Next_Handler(HANDLE, LPPROCESSENTRY32);
//* kernel32.dll!Process32FirstW
typedef BOOL (WINAPI* PROCESS32FIRSTW)(HANDLE, LPPROCESSENTRY32W);
BOOL Process32FirstW_Handler(HANDLE, LPPROCESSENTRY32W);
//* kernel32.dll!Process32NextW
typedef BOOL (WINAPI* PROCESS32NEXTW)(HANDLE, LPPROCESSENTRY32W);
BOOL Process32NextW_Handler(HANDLE, LPPROCESSENTRY32W);
//* kernel32.dll!Module32First
typedef BOOL (WINAPI* MODULE32FIRST)(HANDLE, LPMODULEENTRY32);
BOOL Module32First_Handler(HANDLE, LPMODULEENTRY32);
//* kernel32.dll!Module32Next
typedef BOOL (WINAPI* MODULE32NEXT)(HANDLE, LPMODULEENTRY32);
BOOL Module32Next_Handler(HANDLE, LPMODULEENTRY32);
//* kernel32.dll!Module32FirstW
typedef BOOL (WINAPI* MODULE32FIRSTW)(HANDLE, LPMODULEENTRY32W);
BOOL Module32FirstW_Handler(HANDLE, LPMODULEENTRY32W);
//* kernel32.dll!Module32NextW
typedef BOOL (WINAPI* MODULE32NEXTW)(HANDLE, LPMODULEENTRY32W);
BOOL Module32Next_Handler(HANDLE, LPMODULEENTRY32W);

//* kernel32.dll!IsDebuggerPresent
typedef BOOL (WINAPI *ISDEBUGGERPRESENT)();
BOOL IsDebuggerPresent_Handler();
//* kernel32.dll!WinExec
typedef UINT (WINAPI* WINEXEC)(LPCSTR, UINT);
UINT WinExec_Handler(LPCSTR, UINT);

#endif